### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by tomtom215** [ozkeisar/mockingbird#2]
Hello! 

Thank you for sharing your project, it definitely grabbed my attention to compare against mock server.

Unfortunately, I do not see any license on this repo which is a show stopper for me (and probably for others).

Would you mind adding a license? (MIT and Apache are always preferred 🙃)

**Comment by ozkeisar** [comment]
Hi,
First, i'm very excited that Mockingbird got your attention!
Currently Mockingbird is not an open source project, this i an example project for Mockingbird.
I'm not sure if if you need me to add license to the example project, but let me know.

Regardless, you are more then welcome to download and install mockingbird!
Let me know your thoughts and suggestions.

**Comment by ozkeisar** [comment]
License was added to the project
