### ISSUE TITLE
Mockingbird in a testcontainer

### ISSUE THREAD

**Issue by CosmicTiger** [ozkeisar/mockingbird#3]
Maybe a dumb question but does Mockingbird could have interaction to a testcontainer in order to establish test cases for unit testing?

**Comment by ozkeisar** [comment]
I'm not fimiliar enough with test Containers, can you explain to me what you want to do?

**Comment by zmtmaster** [comment]
@CosmicTiger Did you mean - could it be used within a docker container? 
I guess it can be used for a consistent mocking of presets within a test scope?

We are working on making API for the server start/stop and other commands so it would be wrapped using a Docker, this way you'd probably be able to use it with tools such as TestContainer or any SaaS service, as long as you've configured it properly. 

As I mentions it is a feature we are currently working on.

**Comment by zmtmaster** [comment]
@CosmicTiger We've added support using Docker to runt he server, the API. 
Let us know if you need any assistant.

https://dev.to/ozkeisar/how-to-use-the-mockingbird-docker-image-29mf
