### ISSUE TITLE
Pushing changes to git repo

### ISSUE THREAD

**Issue by ravindrajopo** [ozkeisar/mockingbird#4]
Hi @ozkeisar,

Thanks for all the efforts towards this great tool.  I am new to the tool but with great documentation, I can configure and start the server and hook up with frontend service.

Despite being connected to the remote repo I can see the main and development branches of my remote repo but when I push from the Mockingbird app, nothing is being pushed to the remote.  Do you have any documentation or process to follow?  This will greatly help my team to get the changes that I push to remote.

Once again thanks for the tool.

**Comment by ozkeisar** [comment]
Thanks!

I'm not sure what can be the problem, maybe some rules on your remote git prevent from pushing to main/development branches,

If you want you can access to the local repo that Mockingbird is using and try to perform the Push from terminal manually.

Go to your 'user' folder.

Make sure you can see hidden files. 

In your 'user' folder you will have a folder named '.stub-on-prem'. 

You will have folder named 'repos'.

Under repos you will have list of you projects
 
Go to your project and open terminal. 

Now you can try to perform push manually. 


Let me know if it helped

**Comment by ravindrajopo** [comment]
@ozkeisar,  Despite Mockingbird app successfully connected to the remote GitHub repo during the initial setup I can see remote branches within the app.  
![image](https://github.com/ozkeisar/mockingbird/assets/140174861/be139a64-e447-42f5-935d-b9b7b5d76f18)

So, I assumed the push would push the changes to selected branches from the above screenshot.  I try to push from the terminal as per your suggestion I get the below response.  
![image](https://github.com/ozkeisar/mockingbird/assets/140174861/ae933a2b-535e-475c-a4e9-92d2f3fe5d67).  

And also, after push when I come back to Mockingbird app the created mock apis are all gone and I get the below message.
![image](https://github.com/ozkeisar/mockingbird/assets/140174861/1d8e6e5d-0155-418f-ba6a-44b222eeb3bc)

All were working fine except the git thing but not sure how stable it is to roll across the team I am afraid.

**Comment by ozkeisar** [comment]
It seems there are issues with Git that are unrelated to Mockingbird.
Currently, you're not on a valid Git branch.
Please switch to a valid branch, then try running the 'push' command again.

**Comment by ravindrajopo** [comment]
Sure, I will check out a local branch from the main and try to push.

**Comment by ravindrajopo** [comment]
@ozkeisar Yes, you are correct.  I need to check out a local branch from the main and then push to a remote local branch then create a PR to merge to the main.  Perfect.
