### ISSUE TITLE
Project dropdown not clearing out after project deletion

### ISSUE THREAD

**Issue by ravindrajopo** [ozkeisar/mockingbird#5]
The project dropdown shows all projects even though it's been deleted.
![image](https://github.com/ozkeisar/mockingbird/assets/140174861/925e07dd-ed1a-4dda-aaf0-04edccb851fb)

Not sure whether it's a refresh issue.  I closed the app and reopened it to see the below with deleted projects.
![image](https://github.com/ozkeisar/mockingbird/assets/140174861/5ddbe374-0c53-49fe-a437-89791d3dbf1a)

**Comment by ozkeisar** [comment]
First, thanks for taking the time and effort to report this bug!

i released new beta version with fix for this bug, hope it will fix it

download and install [1.0.9-beta](https://github.com/ozkeisar/mockingbird/releases/tag/1.0.9-beta) 

and then try to perform this action again.
let me know if it fix the bug.

**Comment by ozkeisar** [comment]
Thanks, I'm considering that
