### ISSUE TITLE
Multiple param to GET call

### ISSUE THREAD

**Issue by ravindrajopo** [ozkeisar/mockingbird#6]
Trying to create a "get" the URL to pass more than one param to the api call but can add only one param.  Is there a way I can add more than one parameter?

![image](https://github.com/ozkeisar/mockingbird/assets/140174861/85d64348-dc16-4319-ade8-0888bd4bd01b)
![image](https://github.com/ozkeisar/mockingbird/assets/140174861/d26ad058-e446-4e16-8819-76dbd16104fd)

**Comment by ozkeisar** [comment]
Yes, but it will take me some time,
You can in the meantime use the Function option in the response to build that logic using JS code.

Let me know if you need some examples.
