### ISSUE TITLE
How to use graphql api's on mockingbird

### ISSUE THREAD

**Issue by Prithiviraj1397** [ozkeisar/mockingbird#7]
How can I implement my query in Mockingbird GraphQL

My Query:
query HelloWorld{
  helloWorld{
    message
  }
}
![Capture](https://github.com/ozkeisar/mockingbird/assets/149483705/8cdd8863-61fc-477b-951c-8fe7b1f565c6)

**Comment by ozkeisar** [comment]
First you need to create the parent like that
(schemaPath is for nested queries that not in root, you dont need it in this example)

![image](https://github.com/ozkeisar/mockingbird/assets/34401842/fa9ded12-c54e-4802-8759-95d237315751)

After the parent is created click on 'Add Query' (or 'Add Mutation')

![image](https://github.com/ozkeisar/mockingbird/assets/34401842/763bdb30-f19d-48da-b3a4-ddeb4d35f113)

Then fill the query name like that

![image](https://github.com/ozkeisar/mockingbird/assets/34401842/3c6d26a2-6faf-4667-9cc7-88d01e147a58)

After the query is created click on 'Add response'

![image](https://github.com/ozkeisar/mockingbird/assets/34401842/f5ae4591-700a-4fbd-a9f7-7c38cd61968a)

Then fill the json that you want the query to return

![image](https://github.com/ozkeisar/mockingbird/assets/34401842/54db76a4-9815-43ae-912c-f75ce8b5575b)

After that all setup you you can start the server and open the GraphQL playground by clicking on the link under the query name

![image](https://github.com/ozkeisar/mockingbird/assets/34401842/58b944a0-8cef-4289-9ccb-6e3f94f9f062)


If you have more questions or something not working you are welcome to ask.

Enjoy!

**Comment by ravindrajopo** [comment]
@ozkeisar, Thanks for the quick response in the detailed manner with screenshots.  @Prithiviraj1397 is working in my team.  Appreciate your support on this.

**Comment by ozkeisar** [comment]
Happy to assist

**Comment by Prithiviraj1397** [comment]
After configuring the GraphQL API on Mockingbird, how can I check it?
When I open the GraphQL Playground through Mockingbird, it shows an error.
![image](https://github.com/ozkeisar/mockingbird/assets/149483705/43595a88-83ed-4f1a-bd93-42bef93ee68e)

**Comment by ozkeisar** [comment]
Please add screenshots of the query configuration in mockingbird
Also make sure that you are up to date with the latest version.

**Comment by Prithiviraj1397** [comment]
sure @ozkeisar, Below, I have attached a screenshot for your reference.
![image](https://github.com/ozkeisar/mockingbird/assets/149483705/dc068b1c-d417-4237-940b-34039e29ac37)
![image](https://github.com/ozkeisar/mockingbird/assets/149483705/1b0b1866-3e93-405b-bc12-9f4a84428e30)

**Comment by ozkeisar** [comment]
I released v1.1.0 but its not the issue.
In your response you dont need to add the "data" and the "helloFromCountry"
Simply set {"message":"Hello world country service"} as the response (like in the example).

Let me know if it helped.

**Comment by Prithiviraj1397** [comment]
But in the GraphQL query response, it will return the response mentioned below
Response:
{
  "data": {
    "helloFromCountry": {
      "message": "Hello world Country service"
    }
  }
}

I changed and checked as you told me, but it's not working.
![image](https://github.com/ozkeisar/mockingbird/assets/149483705/29c4740e-c411-4b91-bd59-04ac3bff8c4d)
![image](https://github.com/ozkeisar/mockingbird/assets/149483705/cf820dc6-3e1d-4e32-81d9-8e851be40f59)

**Comment by Prithiviraj1397** [comment]
May i know which time-zone you are in to schedule a call with you please

**Comment by ozkeisar** [comment]
I can on Monday 8pm my time, it is comfortable to you?

**Comment by ravindrajopo** [comment]
It will be too late in India about 9:30 pm IST when your time is 8pm GMT+3.  

For me, it's ok as I am in London. Are you ok to have a call around 6 pm your time?  Need to coordinate between three time zones.

**Comment by ozkeisar** [comment]
Yes

**Comment by ravindrajopo** [comment]
@ozkeisar Please use the below Google Meet link url for the discussion.

https://meet.google.com/xyg-obgs-ipe

To avoid confusion at different times, We will start the call at 3:30 pm GMT (a 30-minute delay from what we had agreed earlier as I have a clash on another task).

@Prithiviraj1397 Please use the above link to join the call.

**Comment by ravindrajopo** [comment]
@ozkeisar FYI, we are joining the call in couple of minutes.

**Comment by ozkeisar** [comment]
@ravindrajopo @Prithiviraj1397 I added the function option in the graphql response, you can download the latest version and try it.

**Comment by ravindrajopo** [comment]
Thanks @ozkeisar for letting us know. I will inform BE Devs accordingly.
