### ISSUE TITLE
A problem with receiving an API in mockingbird server when opening an application on an Android device

### ISSUE THREAD

**Issue by efrat12** [ozkeisar/mockingbird#8]
Hi, 
I try to use mockingbird for receive the API calls when open an Application in my android device.
I set everything I need - the proxy in the device and in the PC, 
I created a new server in mockingbird application that I downloaded to my PC .
It works well with web sites - if I put in my mockingbird server in the target base URL for example https://www.ynet.co.il, I take my server  Server IP that generated in the Servers IP's , I open this link in my android device and it reports the API to mockingbird well. but when I open the web site in chrome - not via the Server IP it does not communicate with mockingbird.
but this is the only way I succeed to report the API to mockingbird.
I need to open an Applicatio in my device and it will report the API from the application to mockingbird, I think I found the target base URL of the specific application I need but also when I put this URL and save it does not communicate with mockingbird when opening the app.
What do I need to do to be able what I need - open an application in my device and catch the API calls to mockingbird? 

maybe I need certificate? where can I find the mockingbird certificate? what else I need?

Thanks a lot!

**Comment by ozkeisar** [comment]
Not sure i understood the issue, you try to open app on android device and you dont see the calls in mockingbird?

does the app baseUrl is targeted to mockingbird IP server? 
does your computer and android device on the same network?

**Comment by efrat12** [comment]
all true.

(I am Nir Gallner's worker, he sent me to use your tool :)  )

**Comment by ozkeisar** [comment]
ask him for my cell number and contact me
